#! /usr/bin/env python
import sferes

def build(bld):
    osg = not bld.all_envs['default']['NO_OSG']
    #libs = 'EIGEN2 ROBDYN BOOST ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR '
    libs = 'EIGEN3 ROBDYN  BOOST BOOST_TIMER ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR ROS BAYESIAN_OPTIMIZATION BOOST_CHRONO RT'
    cxxflags = bld.get_env()['CXXFLAGS']
    if osg:
        libs += ' OSG'

    model = bld.new_task_gen('cxx', 'staticlib')
    model.source = 'hexapod.cc simu.cpp controllerPhase.cpp '
    model.includes = '. ../../ /usr/include /usr/local/include'
    model.target = 'hexapod'
    model.uselib = libs

    modelg = bld.new_task_gen('cxx', 'staticlib')
    modelg.source = 'hexapod.cc simu.cpp controllerPhase.cpp '
    modelg.includes = '. ../../'
    modelg.target = 'hexapodg'
    modelg.uselib = libs
    modelg.cxxflags = cxxflags = ['-DGRAPHIC' ]


    sferes.create_variants(bld,
                           source = 'hexa_cluneexpt_hyperneat.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'hexa_cluneexpt_hyperneat',
                           json = '',
                           variants = ['TEXT'])#, 'ROBOT'])

    sferes.create_variants(bld,
                           source = 'cluneexpt_mapelite.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'cluneexpt_mapelite',
                           json = '',
                           variants = ['TEXT']) #


    if osg:
        print 'osg activated'
        sferes.create_variants(bld,
                           source = 'hexa_cluneexpt_hyperneat.cpp',
                           uselib_local = 'sferes2 hexapodg ',
                           uselib = libs,
                           target = 'hexa_cluneexpt_hyperneat',
                           json = '',
                           variants = ['GRAPHIC'])

        sferes.create_variants(bld,
                           source = 'cluneexpt_mapelite.cpp',
                           uselib_local = 'sferes2 hexapodg',# robot',
                           uselib = libs,
                           target = 'cluneexpt_mapelite',
                           json = '',
                           variants = ['GRAPHIC']) #

