#! /usr/bin/env python
import sferes

def build(bld):
    osg = not bld.all_envs['default']['NO_OSG']
    libs = 'EIGEN3 ROBDYN BOOST ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR '
    cxxflags = bld.get_env()['CXXFLAGS']
    if osg:
        libs += ' OSG'

    model = bld.new_task_gen('cxx', 'staticlib')
    model.source = 'hexapod.cc simu.cpp controllerPhase.cpp '
    model.includes = '. ../../ /usr/include /usr/local/include'
    model.target = 'hexapod'
    model.uselib = libs


    sferes.create_variants(bld,
                           source = 'hexa_coupledcpgwithfb_hyperneat.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'hexa_coupledcpgwithfb_hyperneat',
                           json = '',
                           variants = ['TEXT'])#, 'ROBOT'])

    sferes.create_variants(bld,
                           source = 'coupledcpgwithfb_mapelite.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'coupledcpgwithfb_mapelite',
                           json = '',
                           variants = ['TEXT'])#, 'ROBOT'])

